Review screen
Handees/mobile pull request #31
Opened 2024-04-10 16:58 UTC by balogun14

2024-04-13 08:09 UTC, dro-1 commented on lib/generated/assets.dart
> +///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
What is the purpose of this file?

2024-04-13 08:13 UTC, dro-1 requested changes

2024-04-13 08:13 UTC, dro-1 commented on lib/generated/assets.dart
> +///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
What is the purpose of this file?

2024-04-13 08:13 UTC, dro-1 commented on pubspec.yaml
> +  sdk: ">=2.17.3 >3.0.0"
Why did you change this? Had to change it back to run the code on my laptop.

2024-04-13 08:13 UTC, dro-1 commented on android/app/build.gradle
> +    compileSdkVersion 34//flutter.compileSdkVersion
Why did you change this value as well?

2024-04-13 08:13 UTC, dro-1 commented on lib/apps/customer_app/features/review/ui/review.screen.dart
> +import 'package:flutter/cupertino.dart';
This `ReviewScreen` was not added to the app router so I can't open it. Read this two files to figure out how to add it:
-  https://github.com/Handees/mobile/blob/dev/lib/shared/routes/routers.dart
-  https://github.com/Handees/mobile/blob/dev/lib/shared/routes/routes.dart

2024-04-18 12:58 UTC, dro-1 commented on lib/shared/routes/routers.dart
> +      case CustomerAppRoutes.review:
You were supposed to implement this the way other pages like CustomerAppRoutes.artisanSwitch and CustomerAppRoutes.editPrimary were done and not like CustomerAppRoutes.pickService.

2024-04-18 12:58 UTC, dro-1 commented on lib/generated/assets.dart
> +///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
I'm still wondering how you came about this file?

2024-04-18 13:08 UTC, dro-1 commented on lib/apps/customer_app/features/review/ui/review.screen.dart
> +  final Map<String, bool> _feedback = {
You forgot to add these into the UI and the font of Service Fee and the likes don't look correct.

2024-04-19 15:30 UTC, balogun14 commented
![Uploading Screenshot from 2024-04-19 16-22-06.png…]()

2024-04-27 20:25 UTC, merged